### PR TITLE
Remove prefixes/suffixes from register names

### LINKED ISSUE #4: Remove prefixes on register names
A consequence of parsing from the idf codebase is that many of the register names are uselessly prefixed by the name of the peripheral, e.g https://github.com/esp-rs/esp32/blob/master/src/i2c.rs#L5

Svdtool should be able to patch this.

### LINKED ISSUE #6: Remove `_reg` postfix from registers
Almost all registers uselessly have `_reg` post fixed to them.

### PR DESCRIPTION
**Pull request by jessebraham**
Closes #4, closes #6.

~~Unfortunately this is blocked until stm32-rs/svdtools#2 is merged as I had to add support for `_strip_end` to remove `_REG`, so the Travis build will fail with the current `svdtools` release.~~ I stand corrected

### CODE REVIEW

**Comment by MabezDev** [comment]
Brilliant! Thanks for this. I would like to wait for the svdtools patch to merge if possible, so would you mind pinging me when that has merged?

**Comment by jessebraham** [comment]
Sounds good to me, will let you know when it's merged

**Comment by jeandudey** [comment]
The PR hasn't been merged, perhaps we could add the `svdtools` script to this repo in the meantime? And when the original `svdtools` gets updated switch to that instead to avoid fragmentation.

**Comment by jessebraham** [comment]
I bumped the other PR, see if we can get a response. Worst case we could maintain our own fork of `svdtools` for the time being, and revert to the original when/if things get merged upstream.

**Comment by jeandudey** [comment]
It's there now. :tada:

**Comment by jeandudey** [comment]
@jessebraham In the commit 2dc39ea, shouldn't the `esp32.svd` file be left untouched?

**Comment by jessebraham** [comment]
Possibly, wasn't sure what the procedure was for that. I could have sworn I read somewhere to replace the original but of course now I can't find anything to that effect :wink:

I can revert the changes to that file and add the patched version if that's what is desired.

**Comment by MabezDev** [comment]
@jeandudey correct, but I'll merge this as is and make the changes & note for future contributions. Thank you @jessebraham this will greatly improve the generated API!

**Pull request merged**
