### PR TITLE
Initial codegen

### PR DESCRIPTION
**Pull request by MabezDev**
Initial generation based on an svd generated from https://github.com/MabezDev/idf2svd

Using this svd would look like this
```
let gpio = unsafe { esp32::Peripherals::steal().GPIO };

    // Configure GPIO2 as Output.
    gpio.gpio_enable_w1ts_reg.write(|w| unsafe  { w.bits(0x1 << 2) });
    gpio.gpio_func2_out_sel_cfg_reg.write(|w| unsafe {
        w.bits(0x100)
    });

    loop {
        // turn on gpio
        gpio.gpio_out_w1ts_reg.write(|w| unsafe { w.bits(0x1 << 2) });
        // turn off gpio
        gpio.gpio_out_w1tc_reg.write(|w| unsafe { w.bits(0x1 << 2) });
    }
```

Not quite as nice the hand crafted values by @jeandudey in https://github.com/esp-rs/esp32-hal/pull/2 but we can most likely improve that by improving idf2svd or using svdpatch from stm32-rs (https://github.com/stm32-rs/stm32-rs/issues/284 talks about splitting it out into its own tool)

Thoughts @jeandudey @HarkonenBade?

### CODE REVIEW

**Comment by HarkonenBade** [comment]
Looks interesting! Is there value in doing something like stm32-rs does and building the svd's and transforming them to rust as part of a build.rs script? Rather than checking the resulting rust files into the repo directly. (Penalties are longer initial compile times, benefits are that it's impossible to desync bits of the setup as all the building is done at final compile time)

**Comment by MabezDev** [comment]
That's definitely something we'd want to do I think, the parse and generation time is pretty short anyway.

**Comment by jeandudey** [comment]
> Looks interesting! Is there value in doing something like stm32-rs does and building the svd's and transforming them to rust as part of a build.rs script? Rather than checking the resulting rust files into the repo directly. (Penalties are longer initial compile times, benefits are that it's impossible to desync bits of the setup as all the building is done at final compile time)

I have been trying to create a svd file using the stm32-rs scripts, but it's hard to write a svd file from scratch as the scripts were not created to create them from scratch (at least a boilerplate svd is needed).

Modifying the auto-generated svd files with `svdpatch.py` seems a better option that gives out more flexibility. Also a stand-alone tool (a little bit outated) is on [stm32-rs/svdtools](https://github.com/stm32-rs/svdtools/). For now we can use the tool @MabezDev and use svdpatch scripts as an intermediate step in svd generation later.

**Comment by HarkonenBade** [comment]
Also i've got a version nearly done using the currently unmerged builder methods for the svdparser types, removing the unsafe blocks. However, some of the register names that the idf parser is pulling are invalid under the checks that are performed. In particular it is throwing up register names like `UART_INT_RAW_REG(i)` and svdparser refuses anything other than alphanum and underscores in register names.
Edit: Branch up here: https://github.com/HarkonenBade/idf2svd/tree/svd-builders

**Comment by MabezDev** [comment]
That's excellent! I wasn't aware of the builders, would you mind submitting that as a pr on the idf2svd repo? The unsafe blocks have already bitten me a couple of times already!

> In particular it is throwing up register names like UART_INT_RAW_REG(i)

Yeah I'm aware of that, I opened https://github.com/MabezDev/idf2svd/issues/2 to start discussing how to fix it. obviously removing the `(i)` is simple, but determining how many of each peripheral there are is a bit more tricky. It may just be something we have to hardcode, but I've just pushed https://github.com/MabezDev/idf2svd/pull/3 which parses the interrupt infomation; it seems like this could tell us how many of each there are, e.g there are three global UART interrupts:

```
#define ETS_UART0_INTR_SOURCE                   34/**< interrupt of UART0, level*/
#define ETS_UART1_INTR_SOURCE                   35/**< interrupt of UART1, level*/
#define ETS_UART2_INTR_SOURCE                   36/**< interrupt of UART2, level*/
```
so that would imply 3 uarts exist but I'm not sure how that holds up for the rest of the peripherals.

**Comment by HarkonenBade** [comment]
Noted, pull request created. We may also need to be careful as the builders specify a number of required fields, but throw runtime failures if those fields are not satisfied. So we might need to do a bit of trial and error once we get the names playing nicely to make sure that all the needed fields are being completed.

**Comment by MabezDev** [comment]
Just added support for svd patching, including a few basic patches for adding the indexed peripherals that are missing (addresses https://github.com/MabezDev/idf2svd/issues/2).

I think it might be ready for 0.1.0 release soon, even if its still a little rough around the edges.

**Pull request merged**
